server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/enesdoganoglu/java7configyml"
          default-label: main
          skip-ssl-validation: true
          username: enesdoganoglu
          password: ${GIT_JAVA7_PASSWORD}


